import "./globals.css";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

const Chat = dynamic(() => import("@/components/Chat"));
const Providers = dynamic(() => import("@/components/Providers"));

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <main className="w-screen h-screen text-gray-900 bg-slate-300">
            <Chat />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
